# Generated by Django 5.1.6 on 2025-03-10 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('Client', 'Client'), ('Developer', 'Developer')], default='CLIENT', max_length=255)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('mpesa_number', models.CharField(max_length=11, unique=True)),
                ('payment_details', models.JSONField(blank=True, null=True)),
                ('portfolio_url', models.URLField()),
                ('rating_as_client', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('rating_as_developer', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
