# Generated by Django 5.1.6 on 2025-03-05 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userrole',
            old_name='user_id',
            new_name='user',
        ),
    ]
