# Generated by Django 5.1.6 on 2025-03-05 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_user_id_userprofile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='payment_details',
        ),
    ]
