# Generated by Django 5.1.6 on 2025-03-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_userprofile_payment_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='payment_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rating_as_client',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rating_as_developer',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
