# Generated by Django 5.1.6 on 2025-03-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_userprofile_payment_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role_type',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('DEVELOPER', 'Developer')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
