# Generated by Django 5.1.6 on 2025-03-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_userprofile_role_type_delete_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role_type',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('DEVELOPER', 'Developer')], default='CLIENT', max_length=255),
        ),
    ]
