# Generated by Django 5.1.6 on 2025-03-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_userprofile_role_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role_type',
            field=models.CharField(choices=[('Client', 'Client'), ('Developer', 'Developer')], default='CLIENT', max_length=255),
        ),
    ]
