# Generated by Django 5.1.6 on 2025-03-10 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectrequest',
            old_name='receiver',
            new_name='receiver_email',
        ),
    ]
