# Generated by Django 5.1.6 on 2025-03-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_receiver_projectrequest_receiver_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrequest',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
