# Generated by Django 5.1.6 on 2025-03-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projectrequest_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrequest',
            name='receiver_email',
            field=models.EmailField(max_length=255),
        ),
    ]
