# Generated by Django 5.1.6 on 2025-03-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_projectrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrequest',
            name='sender_email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
