# Generated by Django 5.1.6 on 2025-03-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectrequest_sender_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrequest',
            name='sender_email',
            field=models.EmailField(max_length=255),
        ),
    ]
