# Generated by Django 5.1.6 on 2025-03-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrequest',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
