# Generated by Django 5.1.6 on 2025-03-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_projectrequest_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='payment_status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Processing', 'Processing'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Unpaid', max_length=20),
        ),
    ]
