# Generated by Django 5.1.6 on 2025-06-14 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliverables', '0001_initial'),
        ('projects', '0011_alter_milestone_status_alter_projectrequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_summary', models.CharField(help_text='Short description of the dispute', max_length=255)),
                ('detailed_reason', models.TextField(blank=True, help_text='Detailed explanation of the issue', null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved_by_parties', 'Resolved by Parties'), ('escalated', 'Escalated to Admin'), ('resolved_by_admin', 'Resolved by Admin')], default='open', max_length=30)),
                ('decision', models.CharField(choices=[('client_favored', 'Client Favored'), ('developer_favored', 'Developer Favored'), ('mutual_agreement', 'Mutual Agreement'), ('no_decision', 'No Decision Yet')], default='no_decision', max_length=30)),
                ('is_escalated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('escalation_deadline', models.DateTimeField(help_text='Time by which the issue should be resolved before escalation')),
                ('deliverable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='deliverables.deliverable')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='projects.milestone')),
                ('raised_against', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_against', to=settings.AUTH_USER_MODEL)),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raised_disputes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
