# Generated by Django 5.1.6 on 2025-07-23 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispute',
            options={'ordering': ['-created_at'], 'verbose_name': 'Dispute', 'verbose_name_plural': 'Disputes'},
        ),
    ]
