# Generated by Django 5.1.6 on 2025-03-17 12:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0010_milestone_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestonePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_no', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('mpesa_number', models.CharField(max_length=15)),
                ('checkout_request_id', models.CharField(max_length=200)),
                ('reference', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Complete', 'Complete')], default='Pending', max_length=15)),
                ('receipt_no', models.CharField(blank=True, max_length=200, null=True)),
                ('milestone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='projects.milestone')),
            ],
        ),
    ]
