# Generated by Django 5.1.6 on 2025-06-04 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('projects', '0010_milestone_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestonepayment',
            name='milestone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='projects.milestone'),
        ),
    ]
