# Generated by Django 5.1.6 on 2025-06-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_milestonepayment_milestone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milestonepayment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='milestonepayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default="2025-06-04 12:00"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='milestonepayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='milestonepayment',
            name='checkout_request_id',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='milestonepayment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Complete', 'Complete'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=15),
        ),
    ]
